name: YouTube Auto Reply Bot

on:
  schedule: 
    - cron: '0 * * * *'
    # - cron: '30 2 * * *'   # 08:00 IST
    # - cron: '30 6 * * *'   # 12:00 IST
    # - cron: '30 10 * * *'  # 16:00 IST
    # - cron: '30 14 * * *'  # 20:00 IST
    # - cron: '30 19 * * *'  # 01:00 IST
  workflow_dispatch:

jobs:
  reply-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
        working-directory: .
        run: node index.js
